
[Network]
  Address = ":19132"

[Players]
  Folder = "./data/players"
  MaxCount = 500
  MaximumChunkRadius = 4
  SaveData = false

[Resources]
  Folder = "./data/resources"

[Server]
  AuthEnabled = true
  JoinMessage = ""
  Name = "ยง9SG (Back Soon)"
  QuitMessage = ""
  ShutdownMessage = "ยง9Server closed."

[World]
  Folder = "./data/world"
  Name = "ยง9Lobby"
  SimulationDistance = 8
